---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openclaw.nonnoalex.dev
  resources:
  - openclawinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openclaw.nonnoalex.dev
  resources:
  - openclawinstances/finalizers
  verbs:
  - update
- apiGroups:
  - openclaw.nonnoalex.dev
  resources:
  - openclawinstances/status
  verbs:
  - get
  - patch
  - update
