apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw-dev

resources:
  - ../../base

images:
  - name: controller
    newName: ghcr.io/alessandrolomanto/openclaw-operator
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: openclaw-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
